local_costmap:
  global_frame: map
  robot_base_frame: base_link_1
  #地图更新频率
  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 10 
  #静态地图设置
  static_map: true  
  rolling_window: true
  width: 3
  height: 3
  resolution: 0.05
